version: '3'

services:
  workspace:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db-data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}

volumes:
  db-data: